version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-network

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # environment:
    #   - DATABASE_HOST=db
    #   - DATABASE_NAME=mydatabase
    #   - DATABASE_USER=myuser
    #   - DATABASE_PASSWORD=mypassword
    depends_on:
      - db
    networks:
      - django-network

networks:
  django-network:

volumes:
  postgres_data:
